### CODECASTS Travis CI Setup.

# generic since are docker only builds
language: generic

# requies sudo for Docker executions
sudo: required

# docker must be present
services:
  - docker

before_install:
  # login into the docker registry
  - echo 1

install:
  # build the docker image with the current source code
  - echo 2

script:
  # run the unit tests against the recently built image
  - echo 3