# v2 sintax
version: '2'

# Named volumes
volumes:
  # MySQL Data
  codecasts-mysql-data:
    driver: local

  # Redis Data
  codecasts-redis-data:
    driver: local

  # Elasticsearch Data
  codecasts-elastic-data:
    driver: local

services:
  # MySQL (5.7)
  mysql:
    image: ambientum/mysql:5.7
    container_name: laravel-mysql
    volumes:
      - codecasts-mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=codecasts
      - MYSQL_DATABASE=codecasts
      - MYSQL_USER=codecasts
      - MYSQL_PASSWORD=codecasts

  # Redis
  cache:
    image: ambientum/redis:3.2
    container_name: codecasts-redis
    command: --appendonly yes
    volumes:
      - codecasts-redis-data:/data
    ports:
      - "6379:6379"

  # PHP (with Caddy)
  api:
    image: ambientum/php:7.0-caddy
    container_name: codecasts-php
    volumes:
      - .:/var/www/app
    ports:
      - "80:8080"
    links:
      - mysql
      - cache
      - elastic

# Laravel Queues
  queue:
    image: ambientum/php:7.0
    container_name: laravel-queue
    command: php artisan queue:listen
    volumes:
      - .:/var/www/app
    links:
      - mysql
      - cache
      - elastic

  # Elastic Search
  elastic:
    image: elasticsearch:2.3
    container_name: codecasts-elastic
    volumes:
      - codecasts-elastic-data:/usr/share/elasticsearch/data
    ports:
     - "9200:9200"
     - "9300:9300"